version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx_php_rfi
    volumes:
      - ./src:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    environment:
      - "NGINX_IP_ADDR=${NGINX_IP}"
    networks:
      mynetwork:
        ipv4_address: "${NGINX_IP}"

  php:
    image: php:fpm
    container_name: php_fpm_rfi
    volumes:
      - ./src:/app
      - ./php_fpm/php.ini:/usr/local/etc/php/php.ini
    command: sh -c 'echo "${FLAG}" > /flag.txt && php-fpm'
    networks:
      mynetwork:
        ipv4_address: "${FPM_IP}"

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: "${NET_IP}"
